reading historical weather data:

The data is collected from http://climate.weather.gc.ca/

In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
weather_data = pd.read_csv('data/weather.csv', sep=';')
columns = weather_data.iloc[[13]]
type(columns.values)
columns = columns.values[0][0].replace('"', ' ').split(",")
df = pd.DataFrame([ weather_data.iloc[i].values[0].replace('"', ' ').split(",") for i in range(14,15) ],columns=columns)
df
#len(weather_data.iloc[14].values[0].split(","))

,Date/Time,Year,Month,Day,Time,Data Quality,Temp (°C),Temp Flag,Dew Point Temp (°C),Dew Point Temp Flag,...,Wind Spd Flag,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather
0,2018-01-03 00:00,2018,01,03,00:00,‡,-12.8,,-15.3,,...,,24.1,,99.19,,,,-18,,Blowing Snow

In [3]:
data = [weather_data.iloc[i].values[0].replace('"', ' ').split(",") for i in range(14,len(weather_data)) ]
len(data)

984

Cleaning the weather data: some lines have more than 25 columns:

trying to see what those lines look like:

In [4]:
s1 = [x for x in data if len(x) == 27] 
df1 = pd.DataFrame(s1)
df1

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,2018-01-10 15:00,2018,01,10,15:00,‡,0.8,,0.3,,...,,98.91,,,,,,Rain,Drizzle,Fog

In [5]:
df1[24] = df1[[24, 25, 26]].apply(lambda x: ', '.join(x), axis=1)
df1 = df1.drop([25,26], axis=1)
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,2018-01-10 15:00,2018,01,10,15:00,‡,0.8,,0.3,,...,,2.0,,98.91,,,,,,"Rain, Drizzle, Fog"

In [6]:
s2 = [x for x in data if len(x) == 26] 
df2 = pd.DataFrame(s2)
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,2018-01-03 07:00,2018,01,03,07:00,‡,-11.0,,-15.1,,...,19.3,,98.96,,,,-20,,Snow,Blowing Snow
1,2018-01-03 14:00,2018,01,03,14:00,‡,-7.9,,-10.8,,...,6.4,,98.52,,,,-17,,Snow,Blowing Snow
2,2018-01-03 15:00,2018,01,03,15:00,‡,-7.8,,-10.0,,...,3.2,,98.47,,,,-16,,Snow,Blowing Snow
3,2018-01-03 16:00,2018,01,03,16:00,‡,-7.9,,-9.6,,...,3.6,,98.46,,,,-15,,Snow,Blowing Snow
4,2018-01-03 17:00,2018,01,03,17:00,‡,-7.7,,-9.8,,...,4.8,,98.47,,,,-16,,Snow,Blowing Snow

In [7]:
df2[24] = df2[[24, 25]].apply(lambda x: ', '.join(x), axis=1)
df2 = df2.drop(25, 1)
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,2018-01-03 07:00,2018,01,03,07:00,‡,-11.0,,-15.1,,...,,19.3,,98.96,,,,-20,,"Snow, Blowing Snow"
1,2018-01-03 14:00,2018,01,03,14:00,‡,-7.9,,-10.8,,...,,6.4,,98.52,,,,-17,,"Snow, Blowing Snow"
2,2018-01-03 15:00,2018,01,03,15:00,‡,-7.8,,-10.0,,...,,3.2,,98.47,,,,-16,,"Snow, Blowing Snow"
3,2018-01-03 16:00,2018,01,03,16:00,‡,-7.9,,-9.6,,...,,3.6,,98.46,,,,-15,,"Snow, Blowing Snow"
4,2018-01-03 17:00,2018,01,03,17:00,‡,-7.7,,-9.8,,...,,4.8,,98.47,,,,-16,,"Snow, Blowing Snow"

In [8]:
s3 = [x for x in data if len(x) == 25] 
df3 = pd.DataFrame(s3)
df3.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,2018-01-03 00:00,2018,01,03,00:00,‡,-12.8,,-15.3,,...,,24.1,,99.19,,,,-18,,Blowing Snow
1,2018-01-03 01:00,2018,01,03,01:00,‡,-10.7,,-13.6,,...,,24.1,,99.11,,,,-20,,Cloudy
2,2018-01-03 02:00,2018,01,03,02:00,‡,-10.7,,-14.0,,...,,24.1,,99.08,,,,-20,,Blowing Snow
3,2018-01-03 03:00,2018,01,03,03:00,‡,-10.6,,-14.1,,...,,24.1,,99.06,,,,-20,,NA
4,2018-01-03 04:00,2018,01,03,04:00,‡,-10.6,,-14.3,,...,,24.1,,99.04,,,,-20,,Mostly Cloudy

In [9]:
weather_data = (df1.append([df2, df3])).sort_values(by=0)
weather_data.columns = columns
weather_data

,Date/Time,Year,Month,Day,Time,Data Quality,Temp (°C),Temp Flag,Dew Point Temp (°C),Dew Point Temp Flag,...,Wind Spd Flag,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather
0,2018-01-03 00:00,2018,01,03,00:00,‡,-12.8,,-15.3,,...,,24.1,,99.19,,,,-18,,Blowing Snow
1,2018-01-03 01:00,2018,01,03,01:00,‡,-10.7,,-13.6,,...,,24.1,,99.11,,,,-20,,Cloudy
2,2018-01-03 02:00,2018,01,03,02:00,‡,-10.7,,-14.0,,...,,24.1,,99.08,,,,-20,,Blowing Snow
3,2018-01-03 03:00,2018,01,03,03:00,‡,-10.6,,-14.1,,...,,24.1,,99.06,,,,-20,,NA
4,2018-01-03 04:00,2018,01,03,04:00,‡,-10.6,,-14.3,,...,,24.1,,99.04,,,,-20,,Mostly Cloudy
5,2018-01-03 05:00,2018,01,03,05:00,‡,-9.8,,-13.6,,...,,24.1,,98.97,,,,-19,,Blowing Snow
6,2018-01-03 06:00,2018,01,03,06:00,‡,-9.6,,-12.8,,...,,24.1,,98.96,,,,-17,,Blowing Snow
0,2018-01-03 07:00,2018,01,03,07:00,‡,-11.0,,-15.1,,...,,19.3,,98.96,,,,-20,,"Snow, Blowing Snow"
7,2018-01-03 08:00,2018,01,03,08:00,‡,-11.0,,-14.3,,...,,24.1,,98.94,,,,-19,,NA
8,2018-01-03 09:00,2018,01,03,09:00,‡,-10.7,,-13.3,,...,,19.3,,98.88,,,,-17,,Snow
9,2018-01-03 10:00,2018,01,03,10:00,‡,-9.0,,-12.2,,...,,24.1,,98.84,,,,-17,,Mostly Cloudy
10,2018-01-03 11:00,2018,01,03,11:00,‡,-8.0,,-11.6,,...,,24.1,,98.78,,,,-16,,Snow Showers
11,2018-01-03 12:00,2018,01,03,12:00,‡,-7.8,,-11.7,,...,,24.1,,98.70,,,,-16,,Blowing Snow
12,2018-01-03 13:00,2018,01,03,13:00,‡,-7.7,,-11.6,,...,,19.3,,98.60,,,,-16,,Blowing Snow
1,2018-01-03 14:00,2018,01,03,14:00,‡,-7.9,,-10.8,,...,,6.4,,98.52,,,,-17,,"Snow, Blowing Snow"
2,2018-01-03 15:00,2018,01,03,15:00,‡,-7.8,,-10.0,,...,,3.2,,98.47,,,,-16,,"Snow, Blowing Snow"
3,2018-01-03 16:00,2018,01,03,16:00,‡,-7.9,,-9.6,,...,,3.6,,98.46,,,,-15,,"Snow, Blowing Snow"
4,2018-01-03 17:00,2018,01,03,17:00,‡,-7.7,,-9.8,,...,,4.8,,98.47,,,,-16,,"Snow, Blowing Snow"
5,2018-01-03 18:00,2018,01,03,18:00,‡,-7.8,,-9.5,,...,,8.1,,98.55,,,,-15,,"Snow, Blowing Snow"
6,2018-01-03 19:00,2018,01,03,19:00,‡,-8.3,,-10.2,,...,,4.0,,98.61,,,,-16,,"Snow, Blowing Snow"
7,2018-01-03 20:00,2018,01,03,20:00,‡,-9.2,,-11.7,,...,,12.9,,98.62,,,,-16,,"Snow, Blowing Snow"
13,2018-01-03 21:00,2018,01,03,21:00,‡,-10.0,,-12.2,,...,,9.7,,98.59,,,,-17,,Snow
14,2018-01-03 22:00,2018,01,03,22:00,‡,-10.2,,-12.8,,...,,24.1,,98.56,,,,-17,,Snow
15,2018-01-03 23:00,2018,01,03,23:00,‡,-10.5,,-13.0,,...,,24.1,,98.52,,,,-17,,Snow
16,2018-01-04 00:00,2018,01,04,00:00,‡,-10.4,,-12.9,,...,,19.3,,98.57,,,,-17,,Snow
17,2018-01-04 01:00,2018,01,04,01:00,‡,-10.5,,-12.9,,...,,24.1,,98.49,,,,-17,,Snow
18,2018-01-04 02:00,2018,01,04,02:00,‡,-10.6,,-12.8,,...,,24.1,,98.52,,,,-17,,Snow
19,2018-01-04 03:00,2018,01,04,03:00,‡,-10.6,,-12.6,,...,,24.1,,98.52,,,,-17,,Snow
20,2018-01-04 04:00,2018,01,04,04:00,‡,-10.8,,-12.7,,...,,24.1,,98.44,,,,-17,,Snow
21,2018-01-04 05:00,2018,01,04,05:00,‡,-10.7,,-12.5,,...,,24.1,,98.43,,,,-16,,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,2018-02-11 18:00,2018,02,11,18:00,‡,-0.1,,-1.1,,...,,8.1,,98.04,,,,-6,,"Freezing Rain, Fog"
154,2018-02-11 19:00,2018,02,11,19:00,‡,-1.3,,-2.6,,...,,24.1,,98.32,,,,-8,,"Freezing Rain, Snow"
800,2018-02-11 20:00,2018,02,11,20:00,‡,-2.3,,-4.1,,...,,24.1,,98.54,,,,-9,,NA
801,2018-02-11 21:00,2018,02,11,21:00,‡,-2.9,,-4.8,,...,,24.1,,98.66,,,,-8,,NA
802,2018-02-11 22:00,2018,02,11,22:00,‡,-3.1,,-4.9,,...,,24.1,,98.85,,,,-9,,Mostly Cloudy
803,2018-02-11 23:00,2018,02,11,23:00,‡,-3.5,,-5.7,,...,,24.1,,99.04,,,,-10,,NA
804,2018-02-12 00:00,2018,02,12,00:00,‡,-3.6,,-6.0,,...,,24.1,,99.19,,,,-9,,NA
805,2018-02-12 01:00,2018,02,12,01:00,‡,-3.8,,-6.2,,...,,24.1,,99.33,,,,-10,,Mostly Cloudy
806,2018-02-12 02:00,2018,02,12,02:00,‡,-4.3,,-7.3,,...,,24.1,,99.44,,,,-10,,NA
807,2018-02-12 03:00,2018,02,12,03:00,‡,-5.2,,-7.8,,...,,24.1,,99.59,,,,-13,,NA
808,2018-02-12 04:00,2018,02,12,04:00,‡,-6.6,,-9.0,,...,,24.1,,99.66,,,,-13,,Mainly Clear
809,2018-02-12 05:00,2018,02,12,05:00,‡,-8.0,,-10.3,,...,,24.1,,99.78,,,,-13,,NA
810,2018-02-12 06:00,2018,02,12,06:00,‡,-8.9,,-10.9,,...,,24.1,,99.96,,,,-15,,NA
811,2018-02-12 07:00,2018,02,12,07:00,‡,-9.6,,-11.4,,...,,24.1,,100.05,,,,-15,,Clear
812,2018-02-12 08:00,2018,02,12,08:00,‡,-10.5,,-12.3,,...,,24.1,,100.20,,,,-17,,NA
813,2018-02-12 09:00,2018,02,12,09:00,‡,-9.0,,-11.2,,...,,24.1,,100.35,,,,-16,,NA
814,2018-02-12 10:00,2018,02,12,10:00,‡,-7.6,,-10.4,,...,,24.1,,100.44,,,,-14,,Clear
815,2018-02-12 11:00,2018,02,12,11:00,‡,-6.1,,-9.7,,...,,24.1,,100.52,,,,-13,,NA
816,2018-02-12 12:00,2018,02,12,12:00,‡,-5.2,,-9.3,,...,,24.1,,100.57,,,,-10,,NA
817,2018-02-12 13:00,2018,02,12,13:00,‡,-4.6,,-10.4,,...,,24.1,,100.60,,,,-10,,Mostly Cloudy
818,2018-02-12 14:00,2018,02,12,14:00,‡,-4.9,,-11.2,,...,,24.1,,100.67,,,,-11,,NA
819,2018-02-12 15:00,2018,02,12,15:00,‡,-5.1,,-11.0,,...,,24.1,,100.73,,,,-11,,NA
820,2018-02-12 16:00,2018,02,12,16:00,‡,-4.8,,-10.9,,...,,24.1,,100.80,,,,-11,,Mainly Clear
821,2018-02-12 17:00,2018,02,12,17:00,‡,-5.6,,-11.1,,...,,24.1,,100.91,,,,-12,,NA
822,2018-02-12 18:00,2018,02,12,18:00,‡,-7.3,,-11.5,,...,,24.1,,100.98,,,,-13,,NA
823,2018-02-12 19:00,2018,02,12,19:00,‡,-8.4,,-12.7,,...,,24.1,,101.05,,,,-14,,Mainly Clear
824,2018-02-12 20:00,2018,02,12,20:00,‡,-9.6,,-13.0,,...,,24.1,,101.12,,,,-15,,NA
825,2018-02-12 21:00,2018,02,12,21:00,‡,-10.2,,-13.3,,...,,24.1,,101.18,,,,-14,,NA
826,2018-02-12 22:00,2018,02,12,22:00,‡,-10.9,,-13.8,,...,,24.1,,101.24,,,,-16,,Mostly Cloudy
827,2018-02-12 23:00,2018,02,12,23:00,‡,-11.7,,-14.1,,...,,24.1,,101.27,,,,-17,,NA

In [11]:
weather_data.to_csv('data/weather-data.csv')